### ISSUE TITLE
Error cleaning up temporary directory when cycling quickly between archives

### ISSUE THREAD

**Issue by salty-horse** [multiSnow/mcomix3#109]
This is using the latest code from branch `gtk3`.

1) Visit a directory with multiple archives and run `comix *.cbz`.
2) Before all thumbnails finish generating, switch to the next archive (default hotkey: `<control><shift>N`).

This will generate the following error, and the temporary directory (e.g., `/tmp/mcomix.extractor.u0h9kuen`) will not be deleted.

```
[Thread-36] ERROR: ! Extraction error: Attempt to use ZIP archive that was already closed
Traceback (most recent call last):
  File "mcomix/mcomix/mcomix/event.py", line 291, in key_press_event
    manager.execute((keyval, event.get_state() & ~consumed & ALL_ACCELS_MASK))
  File "mcomix/mcomix/mcomix/keybindings.py", line 147, in execute
    return func(*args, **kwargs)
  File "mcomix/mcomix/mcomix/file_handler.py", line 464, in _open_next_archive
    self._close()
  File "mcomix/mcomix/mcomix/file_handler.py", line 204, in _close
    self._extractor.close()
  File "mcomix/mcomix/mcomix/archive_extractor.py", line 153, in close
    self._archive.close()
  File "mcomix/mcomix/mcomix/archive/archive_recursive.py", line 163, in close
    self._tempdir.cleanup()
  File "/usr/lib/python3.8/tempfile.py", line 971, in cleanup
    self._rmtree(self.name)
  File "/usr/lib/python3.8/tempfile.py", line 953, in _rmtree
    _rmtree(name, onerror=onerror)
  File "/usr/lib/python3.8/shutil.py", line 715, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.8/shutil.py", line 652, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.8/shutil.py", line 656, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/usr/lib/python3.8/shutil.py", line 654, in _rmtree_safe_fd
    os.rmdir(entry.name, dir_fd=topfd)
OSError: [Errno 39] Directory not empty: 'ARCHIVE_NAME_HERE'
```

**Comment by multiSnow** [comment]
https://github.com/multiSnow/mcomix3/tree/fix-race-error try to fix this issue, please test, thanks.

**Comment by salty-horse** [comment]
The patch seems to work well. Thanks!
