### ISSUE TITLE
Does comicthumb really supports pdf?

### ISSUE THREAD

**Issue by rtentser** [multiSnow/mcomix3#123]
In `comicthumb.thumbnailer`

```
[Thumbnailer Entry]
TryExec=comicthumb
Exec=comicthumb %i %o %s
MimeType=application/vnd.comicbook-rar;application/vnd.comicbook+zip;application/x-cb7;application/x-cbt;application/pdf
```
`application/pdf`

But when i try to manually generate thumbnail for pdf i get:

```
Traceback (most recent call last):
  File "/usr/bin/comicthumb", line 69, in <module>
    exit(main())
  File "/usr/bin/comicthumb", line 65, in main
    thumb = thumbnailer.thumbnail(in_path)
  File "/usr/share/mcomix/mcomix/thumbnail_tools.py", line 97, in thumbnail
    return self._create_thumbnail(filepath)
  File "/usr/share/mcomix/mcomix/thumbnail_tools.py", line 168, in _create_thumbnail
    pixbuf, tEXt_data = self._create_thumbnail_pixbuf(filepath)
  File "/usr/share/mcomix/mcomix/thumbnail_tools.py", line 126, in _create_thumbnail_pixbuf
    with archive_tools.get_recursive_archive_handler(
AttributeError: __enter__
```

**Comment by multiSnow** [comment]
mcomix needs `mutool`, provided by mupdf, for pdf support.
see https://github.com/multiSnow/mcomix3/blob/gtk3/README.rst#recommended

**Comment by rtentser** [comment]
Thanks!
