### ISSUE TITLE
Towards a nix package

### ISSUE THREAD

**Issue by con-f-use** [multiSnow/mcomix3#127]
I'm trying to package mcomix3 for the [nix package manager](https://nixos.org).

I'm having this problem:
```
Traceback (most recent call last):
  File "/nix/store/x38kx1vv2yhy44hfqhgfz2scpah1vaf5-mcomix3-1.2.1+git20201123/bin/mcomix/run.py", line 116, in run
    require_version('PangoCairo', '1.0')
  File "/nix/store/4rzakn394b7mfm26hjs7j8xs2liyid9c-python3.8-pygobject-3.36.1/lib/python3.8/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace PangoCairo not available
22:39:37 [MainThread] ERROR: You do not have the required versions of GTK+ 3.0 installed.
```
No idea where it is coming from. I have GTK 3.24.21 installed and pygobject, too.

**Comment by multiSnow** [comment]
Please ensure these files installed correctly, and ask packager of your distribution for more help:
```
girepository-1.0/Atk-1.0.typelib
girepository-1.0/cairo-1.0.typelib
girepository-1.0/Gdk-3.0.typelib
girepository-1.0/GdkPixbuf-2.0.typelib
girepository-1.0/Gio-2.0.typelib
girepository-1.0/GLib-2.0.typelib
girepository-1.0/GModule-2.0.typelib
girepository-1.0/GObject-2.0.typelib
girepository-1.0/Gtk-3.0.typelib
girepository-1.0/HarfBuzz-0.0.typelib
girepository-1.0/Pango-1.0.typelib
girepository-1.0/PangoCairo-1.0.typelib
girepository-1.0/xlib-2.0.typelib
```

**Comment by con-f-use** [comment]
Thanks for the info. I'm currently trying to package mcomix3 for NixOS, so I guess, I'm the packager.

I solved the `PangoCairo` problem and mcomix starts, but in many dialogs or when opening a file it crashes with:

`GLib-GIO-ERROR **: 09:54:45.625: No GSettings schemas are installed on the system`

Any idea, what schema excatctly might be missing or what could be the problem?

See:
 - https://gist.github.com/con-f-use/d7c569c8e3908ffa95e28dd44142f377
 - https://github.com/NixOS/nixpkgs/issues/75028

**Comment by con-f-use** [comment]
Okay, solved that problem, too - the last remaining thing are the tests.

```
==================================== ERRORS ====================================
_________________ ERROR collecting test/test_archive_tools.py __________________
ImportError while importing test module '/build/source/test/test_archive_tools.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/__init__.py:20: in <module>
    import __builtin__
E   ModuleNotFoundError: No module named '__builtin__'
____________________ ERROR collecting test/test_archives.py ____________________
ImportError while importing test module '/build/source/test/test_archives.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/__init__.py:20: in <module>
    import __builtin__
E   ModuleNotFoundError: No module named '__builtin__'
__________________ ERROR collecting test/test_image_tools.py ___________________
ImportError while importing test module '/build/source/test/test_image_tools.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/__init__.py:20: in <module>
    import __builtin__
E   ModuleNotFoundError: No module named '__builtin__'
____________________ ERROR collecting test/test_process.py _____________________
ImportError while importing test module '/build/source/test/test_process.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/__init__.py:20: in <module>
    import __builtin__
E   ModuleNotFoundError: No module named '__builtin__'
=========================== short test summary info ============================
ERROR test/test_archive_tools.py
ERROR test/test_archives.py
ERROR test/test_image_tools.py
ERROR test/test_process.py
```

Are they broken or supposed to work, like at all?

**Comment by multiSnow** [comment]
Sorry, I never dive into the `test` directory (and not well ported to py3 together with mcomix3), so it is not expected working as it was.

**Comment by con-f-use** [comment]
[mcomix3 in nixpkgs](https://github.com/NixOS/nixpkgs/pull/104908)
