### ISSUE TITLE
TypeError: 'map' object is not subscriptable

### ISSUE THREAD

**Issue by bishop23** [multiSnow/mcomix3#8]
Sorry for my English but I use a translator.
I compiled MComix3 on Ubuntu Bionic 18.04. When I start MComix3 the images appear in the sidebar but not in the main window.

```
bishop@ubu23:/usr/local/mcomix$ python3 mcomixstarter.py
Gtk-Message: 11:01:42.205: GtkDialog mapped without a transient parent. This is discouraged.
Traceback (most recent call last):
  File "/usr/local/mcomix/mcomix/main.py", line 424, in _draw_image
    self._show_scrollbars(scrollbar_requests)
  File "/usr/local/mcomix/mcomix/main.py", line 835, in _show_scrollbars
    if limit and request[i]:
TypeError: 'map' object is not subscriptable
```
http://www.casimages.com/i/180324041758349318.png.html

thank you for your work
Bishop23

**Comment by bishop23** [comment]
Dependencies (?) and installation
`sudo apt install libmupdf-dev mupdf unrar python3-dev libpython3-dev p7zip-full p7zip-rar liblhasa-dev python-pil python-gobject-2-dev`

`git clone https://github.com/multiSnow/mcomix3.git`

`cd ~/mcomix3`

```
bishop@ubu23:~/mcomix3$ sudo python3 installer.py --srcdir=mcomix --target=/usr/local
[sudo] Mot de passe de bishop : 
install: mcomix/comicthumb.py /usr/local/mcomix/comicthumb.py
install: mcomix/mcomixstarter.py /usr/local/mcomix/mcomixstarter.py
install: mcomix/mcomix/tools.py /usr/local/mcomix/mcomix/tools.py
install: mcomix/mcomix/about_dialog.py /usr/local/mcomix/mcomix/about_dialog.py
install: mcomix/mcomix/preferences_dialog.py /usr/local/mcomix/mcomix/preferences_dialog.py
install: mcomix/mcomix/slideshow.py /usr/local/mcomix/mcomix/slideshow.py
install: mcomix/mcomix/preferences.py /usr/local/mcomix/mcomix/preferences.py
install: mcomix/mcomix/preferences_page.py /usr/local/mcomix/mcomix/preferences_page.py
install: mcomix/mcomix/openwith_menu.py /usr/local/mcomix/mcomix/openwith_menu.py
install: mcomix/mcomix/main.py /usr/local/mcomix/mcomix/main.py
install: mcomix/mcomix/zoom.py /usr/local/mcomix/mcomix/zoom.py
install: mcomix/mcomix/archive_packer.py /usr/local/mcomix/mcomix/archive_packer.py
install: mcomix/mcomix/recent.py /usr/local/mcomix/mcomix/recent.py
install: mcomix/mcomix/preferences_section.py /usr/local/mcomix/mcomix/preferences_section.py
install: mcomix/mcomix/file_chooser_library_dialog.py /usr/local/mcomix/mcomix/file_chooser_library_dialog.py
install: mcomix/mcomix/run.py /usr/local/mcomix/mcomix/run.py
install: mcomix/mcomix/archive_extractor.py /usr/local/mcomix/mcomix/archive_extractor.py
install: mcomix/mcomix/bookmark_dialog.py /usr/local/mcomix/mcomix/bookmark_dialog.py
install: mcomix/mcomix/file_handler.py /usr/local/mcomix/mcomix/file_handler.py
install: mcomix/mcomix/file_chooser_base_dialog.py /usr/local/mcomix/mcomix/file_chooser_base_dialog.py
install: mcomix/mcomix/keybindings_editor.py /usr/local/mcomix/mcomix/keybindings_editor.py
install: mcomix/mcomix/keybindings.py /usr/local/mcomix/mcomix/keybindings.py
install: mcomix/mcomix/thumbbar.py /usr/local/mcomix/mcomix/thumbbar.py
install: mcomix/mcomix/file_chooser_simple_dialog.py /usr/local/mcomix/mcomix/file_chooser_simple_dialog.py
install: mcomix/mcomix/strings.py /usr/local/mcomix/mcomix/strings.py
install: mcomix/mcomix/bookmark_backend.py /usr/local/mcomix/mcomix/bookmark_backend.py
install: mcomix/mcomix/scrolling.py /usr/local/mcomix/mcomix/scrolling.py
install: mcomix/mcomix/archive_tools.py /usr/local/mcomix/mcomix/archive_tools.py
install: mcomix/mcomix/image_handler.py /usr/local/mcomix/mcomix/image_handler.py
install: mcomix/mcomix/log.py /usr/local/mcomix/mcomix/log.py
install: mcomix/mcomix/layout.py /usr/local/mcomix/mcomix/layout.py
install: mcomix/mcomix/file_provider.py /usr/local/mcomix/mcomix/file_provider.py
install: mcomix/mcomix/image_tools.py /usr/local/mcomix/mcomix/image_tools.py
install: mcomix/mcomix/pageselect.py /usr/local/mcomix/mcomix/pageselect.py
install: mcomix/mcomix/edit_comment_area.py /usr/local/mcomix/mcomix/edit_comment_area.py
install: mcomix/mcomix/openwith.py /usr/local/mcomix/mcomix/openwith.py
install: mcomix/mcomix/thumbnail_tools.py /usr/local/mcomix/mcomix/thumbnail_tools.py
install: mcomix/mcomix/bookmark_menu.py /usr/local/mcomix/mcomix/bookmark_menu.py
install: mcomix/mcomix/event.py /usr/local/mcomix/mcomix/event.py
install: mcomix/mcomix/last_read_page.py /usr/local/mcomix/mcomix/last_read_page.py
install: mcomix/mcomix/message_dialog.py /usr/local/mcomix/mcomix/message_dialog.py
install: mcomix/mcomix/ui.py /usr/local/mcomix/mcomix/ui.py
install: mcomix/mcomix/properties_dialog.py /usr/local/mcomix/mcomix/properties_dialog.py
install: mcomix/mcomix/comment_dialog.py /usr/local/mcomix/mcomix/comment_dialog.py
install: mcomix/mcomix/portability.py /usr/local/mcomix/mcomix/portability.py
install: mcomix/mcomix/process.py /usr/local/mcomix/mcomix/process.py
install: mcomix/mcomix/enhance_dialog.py /usr/local/mcomix/mcomix/enhance_dialog.py
install: mcomix/mcomix/histogram.py /usr/local/mcomix/mcomix/histogram.py
install: mcomix/mcomix/dialog_handler.py /usr/local/mcomix/mcomix/dialog_handler.py
install: mcomix/mcomix/cursor_handler.py /usr/local/mcomix/mcomix/cursor_handler.py
install: mcomix/mcomix/i18n.py /usr/local/mcomix/mcomix/i18n.py
install: mcomix/mcomix/thumbnail_view.py /usr/local/mcomix/mcomix/thumbnail_view.py
install: mcomix/mcomix/edit_image_area.py /usr/local/mcomix/mcomix/edit_image_area.py
install: mcomix/mcomix/worker_thread.py /usr/local/mcomix/mcomix/worker_thread.py
install: mcomix/mcomix/labels.py /usr/local/mcomix/mcomix/labels.py
install: mcomix/mcomix/clipboard.py /usr/local/mcomix/mcomix/clipboard.py
install: mcomix/mcomix/status.py /usr/local/mcomix/mcomix/status.py
install: mcomix/mcomix/callback.py /usr/local/mcomix/mcomix/callback.py
install: mcomix/mcomix/osd.py /usr/local/mcomix/mcomix/osd.py
install: mcomix/mcomix/properties_page.py /usr/local/mcomix/mcomix/properties_page.py
install: mcomix/mcomix/box.py /usr/local/mcomix/mcomix/box.py
install: mcomix/mcomix/edit_dialog.py /usr/local/mcomix/mcomix/edit_dialog.py
install: mcomix/mcomix/enhance_backend.py /usr/local/mcomix/mcomix/enhance_backend.py
install: mcomix/mcomix/bookmark_menu_item.py /usr/local/mcomix/mcomix/bookmark_menu_item.py
install: mcomix/mcomix/icons.py /usr/local/mcomix/mcomix/icons.py
install: mcomix/mcomix/lens.py /usr/local/mcomix/mcomix/lens.py
install: mcomix/mcomix/file_chooser_main_dialog.py /usr/local/mcomix/mcomix/file_chooser_main_dialog.py
install: mcomix/mcomix/__init__.py /usr/local/mcomix/mcomix/__init__.py
install: mcomix/mcomix/constants.py /usr/local/mcomix/mcomix/constants.py
msgfmt: /usr/local/mcomix/mcomix/messages/it/LC_MESSAGES/mcomix.mo mcomix/mcomix/messages/it/LC_MESSAGES/mcomix.po
msgfmt: /usr/local/mcomix/mcomix/messages/sv/LC_MESSAGES/mcomix.mo mcomix/mcomix/messages/sv/LC_MESSAGES/mcomix.po
msgfmt: /usr/local/mcomix/mcomix/messages/pt_BR/LC_MESSAGES/mcomix.mo mcomix/mcomix/messages/pt_BR/LC_MESSAGES/mcomix.po
msgfmt: /usr/local/mcomix/mcomix/messages/ja/LC_MESSAGES/mcomix.mo mcomix/mcomix/messages/ja/LC_MESSAGES/mcomix.po
msgfmt: /usr/local/mcomix/mcomix/messages/he/LC_MESSAGES/mcomix.mo mcomix/mcomix/messages/he/LC_MESSAGES/mcomix.po
msgfmt: /usr/local/mcomix/mcomix/messages/ru/LC_MESSAGES/mcomix.mo mcomix/mcomix/messages/ru/LC_MESSAGES/mcomix.po
msgfmt: /usr/local/mcomix/mcomix/messages/de/LC_MESSAGES/mcomix.mo mcomix/mcomix/messages/de/LC_MESSAGES/mcomix.po
msgfmt: /usr/local/mcomix/mcomix/messages/nl/LC_MESSAGES/mcomix.mo mcomix/mcomix/messages/nl/LC_MESSAGES/mcomix.po
msgfmt: /usr/local/mcomix/mcomix/messages/zh_CN/LC_MESSAGES/mcomix.mo mcomix/mcomix/messages/zh_CN/LC_MESSAGES/mcomix.po
msgfmt: /usr/local/mcomix/mcomix/messages/fa/LC_MESSAGES/mcomix.mo mcomix/mcomix/messages/fa/LC_MESSAGES/mcomix.po
msgfmt: /usr/local/mcomix/mcomix/messages/zh_TW/LC_MESSAGES/mcomix.mo mcomix/mcomix/messages/zh_TW/LC_MESSAGES/mcomix.po
msgfmt: /usr/local/mcomix/mcomix/messages/hu/LC_MESSAGES/mcomix.mo mcomix/mcomix/messages/hu/LC_MESSAGES/mcomix.po
msgfmt: /usr/local/mcomix/mcomix/messages/uk/LC_MESSAGES/mcomix.mo mcomix/mcomix/messages/uk/LC_MESSAGES/mcomix.po
install: mcomix/mcomix/library/control_area.py /usr/local/mcomix/mcomix/library/control_area.py
install: mcomix/mcomix/library/add_progress_dialog.py /usr/local/mcomix/mcomix/library/add_progress_dialog.py
install: mcomix/mcomix/library/main_dialog.py /usr/local/mcomix/mcomix/library/main_dialog.py
install: mcomix/mcomix/library/collection_area.py /usr/local/mcomix/mcomix/library/collection_area.py
install: mcomix/mcomix/library/book_area.py /usr/local/mcomix/mcomix/library/book_area.py
msgfmt: /usr/local/mcomix/mcomix/messages/es/LC_MESSAGES/mcomix.mo mcomix/mcomix/messages/es/LC_MESSAGES/mcomix.po
msgfmt: /usr/local/mcomix/mcomix/messages/gl/LC_MESSAGES/mcomix.mo mcomix/mcomix/messages/gl/LC_MESSAGES/mcomix.po
install: mcomix/mcomix/library/pixbuf_cache.py /usr/local/mcomix/mcomix/library/pixbuf_cache.py
msgfmt: /usr/local/mcomix/mcomix/messages/ko/LC_MESSAGES/mcomix.mo mcomix/mcomix/messages/ko/LC_MESSAGES/mcomix.po
install: mcomix/mcomix/library/watchlist.py /usr/local/mcomix/mcomix/library/watchlist.py
install: mcomix/mcomix/library/backend.py /usr/local/mcomix/mcomix/library/backend.py
install: mcomix/mcomix/library/backend_types.py /usr/local/mcomix/mcomix/library/backend_types.py
install: mcomix/mcomix/library/__init__.py /usr/local/mcomix/mcomix/library/__init__.py
install: mcomix/mcomix/images/mcomix.png /usr/local/mcomix/mcomix/images/mcomix.png
install: mcomix/mcomix/images/comments.png /usr/local/mcomix/mcomix/images/comments.png
install: mcomix/mcomix/images/fitbest.png /usr/local/mcomix/mcomix/images/fitbest.png
install: mcomix/mcomix/images/gimp-rotate-90.png /usr/local/mcomix/mcomix/images/gimp-rotate-90.png
install: mcomix/mcomix/images/library.png /usr/local/mcomix/mcomix/images/library.png
msgfmt: /usr/local/mcomix/mcomix/messages/id/LC_MESSAGES/mcomix.mo mcomix/mcomix/messages/id/LC_MESSAGES/mcomix.po
install: mcomix/mcomix/images/gimp-transform.png /usr/local/mcomix/mcomix/images/gimp-transform.png
install: mcomix/mcomix/images/gimp-flip-horizontal.png /usr/local/mcomix/mcomix/images/gimp-flip-horizontal.png
install: mcomix/mcomix/images/manga.png /usr/local/mcomix/mcomix/images/manga.png
install: mcomix/mcomix/images/gimp-rotate-270.png /usr/local/mcomix/mcomix/images/gimp-rotate-270.png
install: mcomix/mcomix/images/gimp-rotate-180.png /usr/local/mcomix/mcomix/images/gimp-rotate-180.png
install: mcomix/mcomix/images/gimp-thumbnails.png /usr/local/mcomix/mcomix/images/gimp-thumbnails.png
install: mcomix/mcomix/images/tango-add-bookmark.png /usr/local/mcomix/mcomix/images/tango-add-bookmark.png
msgfmt: /usr/local/mcomix/mcomix/messages/hr/LC_MESSAGES/mcomix.mo mcomix/mcomix/messages/hr/LC_MESSAGES/mcomix.po
install: mcomix/mcomix/images/fitsize.png /usr/local/mcomix/mcomix/images/fitsize.png
install: mcomix/mcomix/images/tango-archive.png /usr/local/mcomix/mcomix/images/tango-archive.png
install: mcomix/mcomix/images/fitwidth.png /usr/local/mcomix/mcomix/images/fitwidth.png
install: mcomix/mcomix/images/fitmanual.png /usr/local/mcomix/mcomix/images/fitmanual.png
install: mcomix/mcomix/images/lens.png /usr/local/mcomix/mcomix/images/lens.png
install: mcomix/mcomix/images/tango-image.png /usr/local/mcomix/mcomix/images/tango-image.png
msgfmt: /usr/local/mcomix/mcomix/messages/fr/LC_MESSAGES/mcomix.mo mcomix/mcomix/messages/fr/LC_MESSAGES/mcomix.po
msgfmt: /usr/local/mcomix/mcomix/messages/cs/LC_MESSAGES/mcomix.mo mcomix/mcomix/messages/cs/LC_MESSAGES/mcomix.po
msgfmt: /usr/local/mcomix/mcomix/messages/ca/LC_MESSAGES/mcomix.mo mcomix/mcomix/messages/ca/LC_MESSAGES/mcomix.po
install: mcomix/mcomix/images/mcomix-large.png /usr/local/mcomix/mcomix/images/mcomix-large.png
install: mcomix/mcomix/images/fitheight.png /usr/local/mcomix/mcomix/images/fitheight.png
install: mcomix/mcomix/images/double-page.png /usr/local/mcomix/mcomix/images/double-page.png
install: mcomix/mcomix/images/tango-enhance-image.png /usr/local/mcomix/mcomix/images/tango-enhance-image.png
install: mcomix/mcomix/images/gimp-flip-vertical.png /usr/local/mcomix/mcomix/images/gimp-flip-vertical.png
install: mcomix/mcomix/images/zoom.png /usr/local/mcomix/mcomix/images/zoom.png
install: mcomix/mcomix/images/48x48/mcomix.png /usr/local/mcomix/mcomix/images/48x48/mcomix.png
install: mcomix/mcomix/images/32x32/mcomix.png /usr/local/mcomix/mcomix/images/32x32/mcomix.png
install: mcomix/mcomix/images/24x24/mcomix.png /usr/local/mcomix/mcomix/images/24x24/mcomix.png
msgfmt: /usr/local/mcomix/mcomix/messages/pl/LC_MESSAGES/mcomix.mo mcomix/mcomix/messages/pl/LC_MESSAGES/mcomix.po
install: mcomix/mcomix/images/22x22/mcomix.png /usr/local/mcomix/mcomix/images/22x22/mcomix.png
install: mcomix/mcomix/images/16x16/mcomix.png /usr/local/mcomix/mcomix/images/16x16/mcomix.png
install: mcomix/mcomix/archive/archive_base.py /usr/local/mcomix/mcomix/archive/archive_base.py
install: mcomix/mcomix/archive/zip.py /usr/local/mcomix/mcomix/archive/zip.py
install: mcomix/mcomix/archive/tar.py /usr/local/mcomix/mcomix/archive/tar.py
install: mcomix/mcomix/archive/rar_external.py /usr/local/mcomix/mcomix/archive/rar_external.py
install: mcomix/mcomix/archive/lha_external.py /usr/local/mcomix/mcomix/archive/lha_external.py
install: mcomix/mcomix/archive/archive_recursive.py /usr/local/mcomix/mcomix/archive/archive_recursive.py
install: mcomix/mcomix/archive/sevenzip_external.py /usr/local/mcomix/mcomix/archive/sevenzip_external.py
install: mcomix/mcomix/archive/rar.py /usr/local/mcomix/mcomix/archive/rar.py
msgfmt: /usr/local/mcomix/mcomix/messages/el/LC_MESSAGES/mcomix.mo mcomix/mcomix/messages/el/LC_MESSAGES/mcomix.po
install: mcomix/mcomix/archive/zip_external.py /usr/local/mcomix/mcomix/archive/zip_external.py
install: mcomix/mcomix/archive/pdf_external.py /usr/local/mcomix/mcomix/archive/pdf_external.py
install: mcomix/mcomix/archive/__init__.py /usr/local/mcomix/mcomix/archive/__init__.py

```
